apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  APP_URL: {{ .Values.app.url | quote }}
  KEY_SERVICE_URL: {{ .Values.app.keyServiceUrl | quote }}
  G_URL: {{ .Values.app.gUrl | quote }}
  G_API_URL: {{ .Values.app.gApiUrl | quote }}