apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  CLIENT_ID: {{ .Values.secret.clientId | quote }}
  CLIENT_SECRET: {{ .Values.secret.clientSecret | quote }}