name: Lab 4 Grading

on:
  push:
    branches:
      - lab4

permissions:
  contents: read

jobs:
  helm-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run Grading Script
        run: |
          chmod +x ./tests/lab4_test.sh
          ./tests/lab4_test.sh